### ISSUE TITLE
embed flag should be default true

### ISSUE THREAD

**Issue by isovector** [ekmett/hyphenation#18]
I was just bitten by #3 , in https://github.com/haskell/haskell-language-server/issues/1976, where the entire HLS 1.2.0 release is missing the hyphenation data, and thus fails at runtime. Except that CI doesn't catch this, because CI builds everything from source, and thus has the files available. 

I can empathize with not wanting to bloat binaries, but default behavior that silently fails _at deployment time_ with no early warnings seems like an exceptionally bad choice.

**Comment by vshabanov** [comment]
Thank you for reporting your use case. Just uploaded `hyphenation-0.8.2` with `Embed` set to `True` by default.

**Comment by isovector** [comment]
Thanks so much!
